#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(repoRoot, 'widget', 'src');
const outFile = path.join(repoRoot, 'widget', 'index.coffee');

const sources = fs.readdirSync(srcDir)
  .filter(f => f.endsWith('.coffee'))
  .sort();

if (sources.length === 0) {
  console.error(`No .coffee sources in ${srcDir}`);
  process.exit(1);
}

const HEADER = `# AUTO-GENERATED by scripts/build-widget.mjs from widget/src/*.coffee
# Do not edit this file directly — edit the source files in widget/src/ and run:
#   npm run build:widget

`;

const body = sources
  .map(name => {
    const content = fs.readFileSync(path.join(srcDir, name), 'utf8').replace(/\s+$/, '');
    return `# === ${name} ===\n${content}\n`;
  })
  .join('\n');

fs.writeFileSync(outFile, HEADER + body);
console.log(`Wrote ${path.relative(repoRoot, outFile)} from ${sources.length} sources: ${sources.join(', ')}`);
